services:
  - type: web
    name: ml-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: CONFIG_PATH
        value: "config/config.yaml"
      - key: MLFLOW_TRACKING_URI
        sync: false  # 환경 변수에서 동적으로 가져오기
    healthCheckPath: /_stcore/health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 2