name: MLflow Server
on: 
  push:
    branches: [main]

jobs:
  mlflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install mlflow
      - name: Start MLflow server
        run: |
          mlflow server \
            --host 0.0.0.0 \
            --port 5050 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./mlruns